build: fix the path to `testBuild` folder
Using `../testBuild` caused the following errors:

```
Error:  Error fetching link: /home/runner/work/TweetyProject/TweetyProject/org-tweetyproject-logics-pl/home/runner/work/TweetyProject/TweetyProject/testBuild. Ignored it.
Error:  Error fetching link: /home/runner/work/TweetyProject/TweetyProject/org-tweetyproject-arg-dung/home/runner/work/TweetyProject/TweetyProject/testBuild. Ignored it.
```

Maven seems not to allow output in the parent folder of the project.